<a href="https://colab.research.google.com/github/sohail004/Python-for-Data-Science/blob/main/Copy_of_Intro_to_Numpy_blanks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Copyright 2021, Zaka AI, Inc. All Rights Reserved.

# Introduction to Numpy
---

**Objective:**

In this exercise, you will be covering basics of a  very useful library in Python called Numpy(*Numerical Python is fundamental for scientific computations in python*. Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

Source found [here](http://cs231n.github.io/python-numpy-tutorial/).


In [ ]:
#importing Numpy library
import numpy as np

## Arrays
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [ ]:
# Create a rank 1 array
a = np.array( [2,3,5,1,4] )

print(type(a))            
print(a.shape)           
print(a[-1], a[1], a[2])

<class 'numpy.ndarray'>
(5,)
4 3 5


In [ ]:
# Change an element of the array
a[-1] = 10
print(a)                 

[ 2  3  5  1 10]


In [ ]:
# Create a rank 2 array
b = np.array([ [1,2,3],
               [4,5,6] ,
              [3,7,0]])    

print(b.shape)    

#print elements 1,2, and 4 in the above array
print(b[0,0],b[0,2],b[1,2],b[2,2])

(3, 3)
1 3 6 0


Numpy also provides many functions to create arrays:

In [ ]:
# Create a 3x3 array of all zeros
a = np.zeros ((3,3))
print(a)            

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Create a 1x2 array of all ones
b = np.ones ((1,2))
print(b)

[[1. 1.]]


## Array Indexing

Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [ ]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([ [1,2,3,4], [5,6,7,8], [9,10,11,12] ])
print(a ,a.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4)


In [ ]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:3 , 1:3]
print(b, b.shape)

[[ 2  3]
 [ 6  7]
 [10 11]] (3, 2)


In [ ]:
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.

# b[0, 0] is the same piece of data as a[0, 1]
b[2, 0] = 77
print(a[0, 1])
print(a)

2
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 77 11 12]]


One useful trick with for creating integer arrays is using `arange()` to create an array from numerical ranges:

In [ ]:
#create an array of numbers from 0 to 4 (exclusive)
a= np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
b = np.arange(0,15,2)
b

array([ 0,  2,  4,  6,  8, 10, 12, 14])

## Array Math

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [ ]:
# Elementwise sum of x and y
print(x + y)
# OR
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [ ]:
# Elementwise product of x and y
print(x * y)
# OR
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


Note:

(*) is elementwise multiplication, not matrix multiplication. 

Instead use the (dot function) to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices.

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

# dot product of x and y
print(x.dot(y))
# OR
#print(np.dot(x,y))

[[19 22]
 [43 50]]


## Changing Array Dimensions

In [ ]:
# creating an array a of numbers 0 to 5(inclusive)
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
# reshape a to an array b of dimentions 3x2
b = a.reshape(2, 3)
print('Before reshaping:\n', a)
print('\nAfter reshaping:\n', b)

Before reshaping:
 [0 1 2 3 4 5]

After reshaping:
 [[0 1 2]
 [3 4 5]]


In [ ]:
from numpy.core.fromnumeric import reshape
# reshape b to become a 1x6 array 
c = a.reshape(3,2)
print(c)

[[0 1]
 [2 3]
 [4 5]]
